
//用关键字try,catch捕获异常
//Catch 语句包含要捕获异常类型的声明。

//当保护代码块中发生一个异常时，try 后面的 catch 块就会被检查。
//如果发生的异常包含在 catch 块中，异常会被传递到该 catch 块，
//这和传递一个参数到方法是一样。

//声明有两个元素的一个数组，
//当代码试图访问数组的第四个元素的时候就会抛出一个异常。

//文件名 :ExcepTest.java

import java.io.*;
public class ExcepTest {
	
	public static void main(String[] args) {
		try {
			int a[] = new int[2];
			System.out.println("Access element three :" + a[3]);
		}catch (ArrayIndexOutOfBoundsException e) {
			System.out.println("eception thown :" + e);
		}
		System.out.println("Out of the block");
	}
}